/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARITH_H_RPCGEN
#define _ARITH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct floatpair {
	float a;
	float b;
};
typedef struct floatpair floatpair;

#define ARITH_PROG 0x26E1A3F2
#define ARITH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULT 1
extern  float * mult_1(floatpair *, CLIENT *);
extern  float * mult_1_svc(floatpair *, struct svc_req *);
extern int arith_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULT 1
extern  float * mult_1();
extern  float * mult_1_svc();
extern int arith_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_floatpair (XDR *, floatpair*);

#else /* K&R C */
extern bool_t xdr_floatpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARITH_H_RPCGEN */
